services:
  - type: web
    name: mi-bot-whatsapp
    env: node
    region: oregon
    plan: free
    branch: main
    rootDirectory: ./
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: DISABLE_GPU
        value: "true"
    autoDeploy: true
    healthCheckPath: /health
